/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function scanRepository(root: string, optionsJson?: string | undefined | null): Promise<unknown>

export declare function scanRepositorySync(root: string, optionsJson?: string | undefined | null): string
