/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class CancellationToken {
  constructor()
  cancel(): void
  isCancelled(): boolean
}
export type JsCancellationToken = CancellationToken

export declare class ScanSession {
  static open(root: string, optionsJson?: string | undefined | null, cancellation?: JsCancellationToken | undefined | null): ScanSession
  snapshot(compact?: boolean | undefined | null): string
  exportCache(): string
  updateReason(): string | null
  applyWatchPlan(planJson: string, compact?: boolean | undefined | null, cancellation?: JsCancellationToken | undefined | null): string
  applyWatchPlanAsync(planJson: string, compact?: boolean | undefined | null, cancellation?: JsCancellationToken | undefined | null): Promise<unknown>
  filesPage(generation: number, offset: number, limit: number): string
  fileCursor(): string
  fileCount(): number
}
export type JsScanSession = ScanSession

export declare function exportScanCache(root: string, optionsJson?: string | undefined | null, cancellation?: CancellationToken | undefined | null): Promise<unknown>

export declare function exportScanCacheSync(root: string, optionsJson?: string | undefined | null, cancellation?: CancellationToken | undefined | null): string

export declare function openScanSession(root: string, optionsJson?: string | undefined | null, cancellation?: CancellationToken | undefined | null): Promise<unknown>

export declare function scanDiagnostics(): string

export declare function scanPaths(root: string, optionsJson?: string | undefined | null, cancellation?: CancellationToken | undefined | null): Promise<unknown>

export declare function scanPathsSync(root: string, optionsJson?: string | undefined | null, cancellation?: CancellationToken | undefined | null): Array<string>

export declare function scanRepository(root: string, optionsJson?: string | undefined | null, cancellation?: CancellationToken | undefined | null): Promise<unknown>

export declare function scanRepositorySync(root: string, optionsJson?: string | undefined | null, cancellation?: CancellationToken | undefined | null): string
