/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare class CancellationToken {
  constructor()
  cancel(): void
  isCancelled(): boolean
}

export declare class ScanSession {
  static open(root: string, optionsJson?: string | undefined | null, cancellation?: CancellationToken | undefined | null): ScanSession
  snapshot(compact?: boolean | undefined | null): string
  applyWatchPlan(planJson: string, compact?: boolean | undefined | null): string
  filesPage(offset: number, limit: number): string
  fileCount(): number
}

export declare function scanRepository(root: string, optionsJson?: string | undefined | null, cancellation?: CancellationToken | undefined | null): Promise<string>
export declare function scanRepositorySync(root: string, optionsJson?: string | undefined | null, cancellation?: CancellationToken | undefined | null): string
export declare function scanDiagnostics(): string
